"use client";

import { CalendarCheck2, CircleAlert, Clock3, FileCheck2 } from "lucide-react";
import { useEffect, useState } from "react";
import { AttendanceRegister } from "@/components/attendance-register";
import { PageHeader } from "@/components/page-header";
import { StatCard } from "@/components/stat-card";

type Summary = { todayRate: number; counts: { present: number; absent: number; late: number; excused: number }; classWise: { className: string; present: number; total: number; rate: number }[]; monthly: { month: string; rate: number }[] };

export function AttendanceDashboard() {
  const [summary, setSummary] = useState<Summary | null>(null);
  useEffect(() => { fetch("/api/attendance/summary").then((response) => response.json()).then((data) => setSummary(data)).catch(() => setSummary(null)); }, []);
  const counts = summary?.counts ?? { present: 0, absent: 0, late: 0, excused: 0 };
  return <div><PageHeader eyebrow="Daily operations" title="Attendance" description="Track daily attendance for students and teaching staff." /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Today's rate" value={`${summary?.todayRate ?? 0}%`} detail="Present and late combined" icon={CalendarCheck2} /><StatCard label="Present" value={String(counts.present)} detail="Marked present today" icon={CalendarCheck2} /><StatCard label="Absent" value={String(counts.absent)} detail="Follow-up required" icon={CircleAlert} tone="rose" /><StatCard label="Late / excused" value={String(counts.late + counts.excused)} detail={`${counts.late} late · ${counts.excused} excused`} icon={Clock3} tone="orange" /></div><div className="mb-6 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><section className="rounded-2xl border border-[#e3e9eb] bg-white p-5 shadow-[0_5px_20px_rgba(24,35,47,0.03)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Class-wise attendance</h2><p className="mt-1 text-xs text-slate-500">Today&apos;s attendance by class</p></div><CalendarCheck2 size={18} className="text-[#1c5b4d]" /></div><div className="space-y-5">{summary?.classWise.map((item) => <div key={item.className}><div className="mb-2 flex justify-between text-xs font-semibold"><span>Grade {item.className}</span><span className="text-slate-500">{item.rate}% · {item.present}/{item.total}</span></div><div className="h-2 rounded-full bg-[#edf1f1]"><div className="h-2 rounded-full bg-[#6fae9b]" style={{ width: `${item.rate}%` }} /></div></div>)}</div></section><section className="rounded-2xl border border-[#e3e9eb] bg-white p-5 shadow-[0_5px_20px_rgba(24,35,47,0.03)]"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Monthly summary</h2><p className="mt-1 text-xs text-slate-500">School-wide attendance trend</p></div><FileCheck2 size={18} className="text-[#46718d]" /></div><div className="flex h-36 items-end gap-3">{summary?.monthly.map((item) => <div key={item.month} className="flex flex-1 flex-col items-center gap-2"><span className="text-[10px] font-semibold text-slate-500">{item.rate}%</span><div className="flex h-24 w-full items-end rounded-lg bg-[#f1f6f4]"><div className="w-full rounded-lg bg-[#7b9fba]" style={{ height: `${item.rate}%` }} /></div><span className="text-[11px] text-slate-500">{item.month}</span></div>)}</div></section></div><AttendanceRegister /></div>;
}
