export type OperationModule = "fees" | "exams" | "timetable" | "announcements" | "reports" | "parent-portal" | "student-portal" | "teacher-portal";

type OperationData = { title: string; summary: string; stats: { label: string; value: string; detail: string; tone?: "green" | "orange" | "blue" | "rose" }[]; sections: { title: string; description: string; rows: Record<string, string>[] }[] };

const data: Record<OperationModule, OperationData> = {
  fees: { title: "Fees & billing", summary: "Manage fee structures, collections, receipts and outstanding balances.", stats: [{ label: "Collected this month", value: "Rs 8.4L", detail: "68% of monthly target" }, { label: "Outstanding", value: "Rs 3.9L", detail: "Across 184 invoices", tone: "orange" }, { label: "Defaulters", value: "42", detail: "Requires follow-up", tone: "rose" }], sections: [{ title: "Recent collections", description: "Payment history and receipts", rows: [{ Invoice: "INV-2841", Student: "Riya Kapoor", Category: "Term 2 tuition", Amount: "Rs 24,500", Status: "Paid" }, { Invoice: "INV-2839", Student: "Aarav Mehta", Category: "Transport", Amount: "Rs 8,400", Status: "Paid" }, { Invoice: "INV-2824", Student: "Kabir Shah", Category: "Term 2 tuition", Amount: "Rs 24,500", Status: "Pending" }] }, { title: "Fee structure", description: "Current academic year categories", rows: [{ Category: "Tuition", Structure: "Rs 72,000 / year", Assigned: "1,248 students", Status: "Active" }, { Category: "Transport", Structure: "Rs 24,000 / year", Assigned: "426 students", Status: "Active" }, { Category: "Activities", Structure: "Rs 8,000 / year", Assigned: "1,012 students", Status: "Active" }] }] },
  exams: { title: "Exams & assessments", summary: "Plan schedules, enter marks, calculate grades and publish report cards.", stats: [{ label: "Upcoming exams", value: "3", detail: "Next starts in 7 days" }, { label: "Marks entered", value: "84%", detail: "Mid-term assessments", tone: "blue" }, { label: "Reports published", value: "48%", detail: "Parent visibility enabled", tone: "orange" }], sections: [{ title: "Exam schedule", description: "Upcoming assessments", rows: [{ Exam: "Mid-term assessments", Grades: "6 - 10", Dates: "18 - 28 Mar 2025", Subjects: "18", Status: "Upcoming" }, { Exam: "Annual examinations", Grades: "1 - 12", Dates: "02 - 16 May 2025", Subjects: "32", Status: "Planning" }, { Exam: "Unit test 3", Grades: "11 - 12", Dates: "24 - 28 Mar 2025", Subjects: "12", Status: "Upcoming" }] }, { title: "Marks entry", description: "Teacher progress by subject", rows: [{ Subject: "Mathematics", Teacher: "Vikram Singh", Class: "8A", Entered: "38 / 40", Status: "In progress" }, { Subject: "English Literature", Teacher: "Ishita Verma", Class: "8C", Entered: "40 / 40", Status: "Complete" }] }] },
  timetable: { title: "Timetable", summary: "Manage classes, sections, subjects, teacher allocation and weekly schedules.", stats: [{ label: "Active classes", value: "42", detail: "Across grades 1 to 12" }, { label: "Weekly periods", value: "1,008", detail: "Fully allocated", tone: "blue" }, { label: "Open allocations", value: "6", detail: "Need a teacher", tone: "orange" }], sections: [{ title: "Monday schedule", description: "Grade 8A weekly timetable", rows: [{ Time: "08:30", Subject: "Mathematics", Teacher: "Vikram Singh", Room: "204" }, { Time: "09:20", Subject: "English Literature", Teacher: "Ishita Verma", Room: "204" }, { Time: "10:30", Subject: "Physics", Teacher: "Dev Malhotra", Room: "Lab 1" }, { Time: "11:20", Subject: "Social Studies", Teacher: "Sana Khan", Room: "204" }] }, { title: "Teacher allocation", description: "Current subject ownership", rows: [{ Class: "8A", Subject: "Mathematics", Teacher: "Vikram Singh", Periods: "5 / week" }, { Class: "8A", Subject: "English", Teacher: "Ishita Verma", Periods: "4 / week" }] }] },
  announcements: { title: "Announcements", summary: "Create, publish and target communications by role.", stats: [{ label: "Published", value: "18", detail: "This academic year" }, { label: "Drafts", value: "4", detail: "Awaiting review", tone: "orange" }, { label: "Reach", value: "3,842", detail: "Active recipients", tone: "blue" }], sections: [{ title: "Published announcements", description: "Recent school communications", rows: [{ Title: "Parent orientation", Audience: "Parents", Published: "Today", Status: "Published" }, { Title: "Annual day rehearsal", Audience: "Students, Teachers", Published: "10 Mar 2025", Status: "Published" }, { Title: "Fee deadline reminder", Audience: "Parents", Published: "08 Mar 2025", Status: "Published" }] }, { title: "Create announcement", description: "Prepare a role-targeted message", rows: [{ Field: "Audience", Value: "Parents, Students, Teachers", Required: "Yes" }, { Field: "Publish date", Value: "11 Mar 2025", Required: "Yes" }] }] },
  reports: { title: "Reports", summary: "Review attendance, fee, academic and student performance reports.", stats: [{ label: "Attendance rate", value: "96.2%", detail: "Current month" }, { label: "Fee collection", value: "81.4%", detail: "Current term", tone: "orange" }, { label: "Average score", value: "78.6%", detail: "Mid-term results", tone: "blue" }], sections: [{ title: "Available reports", description: "Exportable school insights", rows: [{ Report: "Daily attendance", Scope: "All classes", Updated: "Today, 9:12 AM", Format: "PDF / CSV" }, { Report: "Fee defaulters", Scope: "Term 2", Updated: "Today, 8:40 AM", Format: "PDF / CSV" }, { Report: "Academic performance", Scope: "Mid-term", Updated: "Yesterday", Format: "PDF / CSV" }, { Report: "Student performance", Scope: "All students", Updated: "Yesterday", Format: "PDF / CSV" }] }] },
  "parent-portal": { title: "Parent portal", summary: "Everything your family needs for Aarav's school journey.", stats: [{ label: "Attendance", value: "96.2%", detail: "This academic year" }, { label: "Fees due", value: "Rs 24,500", detail: "Term 2 tuition", tone: "orange" }, { label: "Average score", value: "82%", detail: "Latest assessment", tone: "blue" }], sections: [{ title: "Child profile", description: "Aarav Mehta · Grade 8A", rows: [{ Item: "Class", Value: "Grade 8A", Status: "Active" }, { Item: "Class teacher", Value: "Vikram Singh", Status: "Contact school" }] }, { title: "Announcements", description: "Messages for your family", rows: [{ Title: "Parent orientation", Date: "Today", Status: "Unread" }, { Title: "Fee deadline reminder", Date: "08 Mar 2025", Status: "Read" }] }] },
  "student-portal": { title: "Student portal", summary: "Your profile, attendance, fees, results and timetable in one place.", stats: [{ label: "Attendance", value: "96.2%", detail: "This academic year" }, { label: "Current average", value: "82%", detail: "Latest assessment", tone: "blue" }, { label: "Next class", value: "Mathematics", detail: "Today at 8:30 AM", tone: "orange" }], sections: [{ title: "My results", description: "Latest published grades", rows: [{ Subject: "Mathematics", Score: "88 / 100", Grade: "A" }, { Subject: "English Literature", Score: "82 / 100", Grade: "A" }, { Subject: "Physics", Score: "76 / 100", Grade: "B+" }] }, { title: "Today&apos;s timetable", description: "Grade 8A", rows: [{ Time: "08:30", Subject: "Mathematics", Room: "204" }, { Time: "09:20", Subject: "English Literature", Room: "204" }, { Time: "10:30", Subject: "Physics", Room: "Lab 1" }] }] },
  "teacher-portal": { title: "Teacher portal", summary: "Your assigned classes, rosters, attendance and marks entry.", stats: [{ label: "Assigned classes", value: "3", detail: "8A, 9B, 10A" }, { label: "Attendance today", value: "100%", detail: "8A completed", tone: "green" }, { label: "Marks pending", value: "2", detail: "Assessment tasks", tone: "orange" }], sections: [{ title: "Assigned classes", description: "Current teaching roster", rows: [{ Class: "8A", Subject: "Mathematics", Students: "32", Attendance: "Complete" }, { Class: "9B", Subject: "Mathematics", Students: "30", Attendance: "Pending" }, { Class: "10A", Subject: "Mathematics", Students: "28", Attendance: "Pending" }] }, { title: "Marks entry", description: "Assessment tasks", rows: [{ Assessment: "Mid-term Mathematics", Class: "8A", Progress: "32 / 32", Status: "Complete" }, { Assessment: "Unit test 3", Class: "9B", Progress: "18 / 30", Status: "In progress" }] }] },
};

export function getOperations(module: OperationModule) { return data[module]; }
export function listOperationModules() { return Object.keys(data) as OperationModule[]; }
